#admin
mesclics_admin_clients:
    path: /
    defaults: { _controller: MesClicsEspaceClientBundle:Admin:getClients }

mesclics_admin_client:
    path:   /{client_id}/
    defaults: { _controller: MesClicsEspaceClientBundle:Admin:getClient }

mesclics_admin_client_edit:
    path: /{client_id}/edit/
    defaults: { _controller: MesClicsEspaceClientBundle:Admin:postClient }

mesclics_admin_client_projets:
    path: /{client_id}/projets/
    defaults: { _controller: MesClicsEspaceClientBundle:Admin:getClientProjects }

mesclics_admin_client_projet:
    path: /{client_id}/projets/{projet_id}/
    defaults: { _controller: MesClicsEspaceClientBundle:Admin:getClientProject }

mesclics_admin_client_contrats:
    path: /{client_id}/contracts/
    defaults: { _controller: MesClicsEspaceClientBundle:Admin:getClientContracts }

mesclics_admin_client_contrat:
    path: /{client_id}/contracts/{contrat_id}/
    defaults: { _controller: MesClicsEspaceClientBundle:Admin:getClientContract }

#espace_client
mesclics_espace_client:
    path:    /{client}/{section}
    defaults: 
        _controller: MesClicsEspaceClientBundle:Main:index
        section:     index 
    requirements:
        section: ((index)|(charte)|(charte-graphique)|(contrat)|(profil))[\/]?

mesclics_espace_client_test:
    path: /test/{var}
    defaults:
        _controller: MesClicsEspaceClientBundle:Main:test

mesclics_espace_client_test_update:
    path:    /test/update/{id}/{numero}
    defaults:
        _controller: MesClicsEspaceClientBundle:Main:update

mesclics_espace_client_test_add:
    path:    /test/add/{nom}/{prospect}
    defaults:
         _controller: MesClicsEspaceClientBundle:Main:addClient
         prospect: false
