#admin
mesclics_admin_clients:
    path: /
    defaults: { _controller: MesClicsEspaceClientBundle:Client:clients }

mesclics_admin_client:
    path:   /{client_id}/
    defaults: { _controller: MesClicsEspaceClientBundle:Client:get }

# PROJETS
mesclics_admin_client_projets:
    path: /{client_id}/projets/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:projets }

mesclics_admin_client_projets_add:
    path: /{client_id}/projets/new/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:post }

mesclics_admin_client_projet:
    path: /{client_id}/projets/{projet_id}/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:update }

mesclics_admin_client_projet_delete:
    path: /{client_id}/projets/{projet_id}/delete/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:delete }

mesclics_admin_client_projet_remove:
    path: /{client_id}/projets/{projet_id}/remove/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:remove }

mesclics_admin_client_projet_attach_confirm:
    path: /{contrat_id}/projets/{projet_id}/attach/proceed/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:proceedAttach }

mesclics_admin_client_projet_attach:
    path: /{contrat_id}/projets/{projet_id}/attach/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:attach }
    
mesclics_admin_client_projet_detach_confirm:
    path: /{client_id}/projets/{projet_id}/detach/proceed/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:proceedDetach }

mesclics_admin_client_projet_detach:
    path: /{client_id}/projets/{projet_id}/detach/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:detach }


# CONTRATS
mesclics_admin_client_contrats:
    path: /{client_id}/contrats/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientContrat:contrats }

mesclics_admin_client_contrats_add:
    path: /{client_id}/contrats/new/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientContrat:post }

mesclics_admin_client_contrat:
    path: /{client_id}/contrats/{contrat_id}/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientContrat:get }

mesclics_admin_client_contrat_delete:
    path: /{client_id}/contrats/{contrat_id}/delete/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientContrat:delete }

mesclics_admin_client_contrat_remove:
    path: /{client_id}/contrats/{contrat_id}/remove/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientContrat:remove }

#espace_client
mesclics_espace_client:
    path:    /{client}/{section}
    defaults: 
        _controller: MesClicsEspaceClientBundle:Main:index
        section:     index 
    requirements:
        section: ((index)|(charte)|(charte-graphique)|(contrat)|(profil))[\/]?

mesclics_espace_client_test:
    path: /test/{var}
    defaults:
        _controller: MesClicsEspaceClientBundle:Main:test

mesclics_espace_client_test_update:
    path:    /test/update/{id}/{numero}
    defaults:
        _controller: MesClicsEspaceClientBundle:Main:update

mesclics_espace_client_test_add:
    path:    /test/add/{nom}/{prospect}
    defaults:
         _controller: MesClicsEspaceClientBundle:Main:addClient
         prospect: false
