#admin
mesclics_admin_clients:
    path: /
    defaults: { _controller: MesClicsEspaceClientBundle:Admin:clients }

mesclics_admin_client:
    path:   /{client_id}/
    defaults: { _controller: MesClicsEspaceClientBundle:Client:get }

mesclics_admin_client_add:
    path: /add/
    defaults: { _controller: MesClicsEspaceClientBundle:Client:post }

mesclics_admin_client_update:
    path: /{client_id}/edit/
    defaults: { _controller: MesClicsEspaceClientBundle:Client:update }

# PROJETS
mesclics_admin_client_projets:
    path: /{client_id}/projets/
    defaults: { _controller: MesClicsEspaceClientBundle:Client:projets }

mesclics_admin_client_projets_add:
    path: /{client_id}/projets/new/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:post }

mesclics_admin_client_projet:
    path: /{client_id}/projets/{projet_id}/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:update }

mesclics_admin_client_projet_remove:
    path: /{client_id}/projets/{projet_id}/remove/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientProjet:remove }

# CONTRATS
mesclics_admin_client_contrats:
    path: /{client_id}/contrats/
    defaults: { _controller: MesClicsEspaceClientBundle:Client:contrats }

mesclics_admin_client_contrats_add:
    path: /{client_id}/contrats/new/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientContrats:post }

mesclics_admin_client_contrat:
    path: /{client_id}/contrats/{contrat_id}/
    defaults: { _controller: MesClicsEspaceClientBundle:ClientContrats:get }

#espace_client
mesclics_espace_client:
    path:    /{client}/{section}
    defaults: 
        _controller: MesClicsEspaceClientBundle:Main:index
        section:     index 
    requirements:
        section: ((index)|(charte)|(charte-graphique)|(contrat)|(profil))[\/]?

mesclics_espace_client_test:
    path: /test/{var}
    defaults:
        _controller: MesClicsEspaceClientBundle:Main:test

mesclics_espace_client_test_update:
    path:    /test/update/{id}/{numero}
    defaults:
        _controller: MesClicsEspaceClientBundle:Main:update

mesclics_espace_client_test_add:
    path:    /test/add/{nom}/{prospect}
    defaults:
         _controller: MesClicsEspaceClientBundle:Main:addClient
         prospect: false
