<?php

namespace MesClics\EspaceClientBundle\Repository;

/**
 * ArticleQuantiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleQuantiteRepository extends \Doctrine\ORM\EntityRepository
{
}
