<?php

namespace MesClics\EspaceClientBundle\Repository;

/**
 * CharteGraphiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharteGraphiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
