<?php

namespace MesClics\EspaceClientBundle\Repository;

use MesClics\EspaceClientBundle\Entity\Client;

/**
 * ContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratRepository extends \Doctrine\ORM\EntityRepository
{
    public function getContratWithProjects(){
        $qb = $this
        ->createQueryBuilder('contrat')
        ->leftJoin('contrat.projets', 'projet')
        ->addSelect('projet')
        ;

        return $qb->getQuery()->getResult();
    }

    public function getContratsQB(Client $client){
        $qb = $this
        ->createQueryBuilder('contrat')
        ->andWhere('contrat.client = :client')
        ->setParameter('client', $client)
        ;

        return $qb;
    }

    public function getNumeroOrder($numero){
        $qb = $this
        ->createQueryBuilder('contrat');
        $qb
        ->andWhere($qb->expr()->like('contrat.numero', ':numero'))
            ->setParameter('numero', $numero . '%')
        ->select($qb->expr()->count('contrat'))
        ;
    
        return $qb->getQuery()->getSingleScalarResult();
    }
}
