<?php

namespace MesClics\EspaceClientBundle\Repository;

/**
 * ElementGraphiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementGraphiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
